import {
  IconAlertCircle,
  IconAperture,
  IconAppWindow,
  IconApps,
  IconAward,
  IconBan,
  IconBasket,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderStyle2,
  IconBorderTop,
  IconBorderVertical,
  IconBox,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBoxMultiple,
  IconCalendar,
  IconChartArcs,
  IconChartArea,
  IconChartCandle,
  IconChartDonut3,
  IconChartDots,
  IconChartLine,
  IconChartRadar,
  IconCurrencyDollar,
  IconEdit,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconGitMerge,
  IconHelp,
  IconLayout,
  IconLockAccess,
  IconLogin,
  IconMail,
  IconMessage2,
  IconMoodSmile,
  IconNotes,
  IconPackage,
  IconPoint,
  IconRotate,
  IconSettings,
  IconShoppingCart,
  IconStar,
  IconTicket,
  IconUserCircle,
  IconUserPlus,
  IconZoomCode,
} from '@tabler/icons';

import { uniqueId } from 'lodash';

const Menuitems = [
  {
    id: uniqueId(),
    title: 'Industry',
    icon: IconAperture,
    href: '/overview/Industry',
    chip: 'New',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Economy',
    icon: IconCurrencyDollar,
    href: '/econometrics/EconomicData',
  },
  {
    navlabel: true,
    subheader: 'World',
  },
  {
    id: uniqueId(),
    title: 'World Energy Report',
    icon: IconChartLine,
    href: '/World/WorldData',
  },
  {
    navlabel: true,
    subheader: 'Africa',
  },
  {
    id: uniqueId(),
    title: 'Africa',
    icon: IconBox,
    href: '/Africa/AfricaData',
  },
  {
    id: uniqueId(),
    title: 'West Africa',
    icon: IconPackage,
    href: '/Africa/WestAfricaData',
  },
  {
    navlabel: true,
    subheader: 'On-Grid',
  },
  {
    id: uniqueId(),
    title: 'Generation',
    icon: IconChartCandle,
    href: '/On-Grid/GenerationData',
  },
  {
    id: uniqueId(),
    title: 'Transmission',
    icon: IconGitMerge,
    href: '/transmission/TransmissionData',
  },
  {
    id: uniqueId(),
    title: 'Distribution',
    icon: IconApps,
    href: '/distribution/Disco',
  },
  {
    id: uniqueId(),
    title: 'Customer',
    icon: IconUserCircle,
    href: '/customer/CustomerData',
  },
  {
    navlabel: true,
    subheader: 'Off-Grid',
  },
  {
    id: uniqueId(),
    title: 'Mini Grids',
    icon: IconBoxMultiple,
    href: '/off-grid/MiniGridsData',
  },
  {
    navlabel: true,
    subheader: 'Energy Insights',
  },
  {
    id: uniqueId(),
    title: 'Reports',
    icon: IconFileDescription,
    href: '/off-grid/EnergyReportData',
  },
  {
    navlabel: true,
    subheader: 'Datasets',
  },
  {
    id: uniqueId(),
    title: 'Datasets',
    icon: IconFiles,
    href: '/dataset/Dataset_Data',
  },
];

export default Menuitems;
